/**
 * Society Maintenance Tracker — database schema.
 *
 * Design decisions that matter for review:
 *
 *  • `complaintEvents` is a single append-only audit log covering both status
 *    and priority changes, rather than two near-identical history tables.
 *    Rationale in docs/SYSTEM_DESIGN.md. Immutability is enforced by a
 *    database trigger (see migration 0001), not merely by convention in the
 *    service layer.
 *
 *  • Overdue is NOT a column. It is derived from
 *    (status, createdAt, appSettings.overdueThresholdDays) so that changing
 *    the threshold instantly re-classifies every complaint everywhere.
 *    `src/lib/overdue.ts` is the single source of truth for that rule.
 *
 *  • `complaints.reference` is generated by a PostgreSQL sequence via a column
 *    default, making it atomic and race-free under concurrent inserts.
 */
import { relations, sql } from 'drizzle-orm';
import {
  boolean,
  check,
  index,
  integer,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const roleEnum = pgEnum('role', ['RESIDENT', 'ADMIN']);

export const complaintStatusEnum = pgEnum('complaint_status', ['OPEN', 'IN_PROGRESS', 'RESOLVED']);

export const priorityEnum = pgEnum('priority', ['LOW', 'MEDIUM', 'HIGH']);

export const complaintCategoryEnum = pgEnum('complaint_category', [
  'PLUMBING',
  'ELECTRICAL',
  'CLEANING',
  'SECURITY',
  'ELEVATOR',
  'WATER_SUPPLY',
  'COMMON_AREA',
  'PARKING',
  'NOISE',
  'PEST_CONTROL',
  'OTHER',
]);

export const complaintEventTypeEnum = pgEnum('complaint_event_type', [
  'CREATED',
  'STATUS_CHANGED',
  'PRIORITY_CHANGED',
]);

export const emailTypeEnum = pgEnum('email_type', [
  'COMPLAINT_STATUS_CHANGED',
  'IMPORTANT_NOTICE',
]);

export const emailStatusEnum = pgEnum('email_status', ['PENDING', 'SENT', 'FAILED']);

// ---------------------------------------------------------------------------
// Identity
// ---------------------------------------------------------------------------

export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    email: varchar('email', { length: 255 }).notNull().unique(),
    passwordHash: text('password_hash').notNull(),
    fullName: varchar('full_name', { length: 120 }).notNull(),
    flatNumber: varchar('flat_number', { length: 20 }).notNull(),
    phone: varchar('phone', { length: 20 }),
    role: roleEnum('role').notNull().default('RESIDENT'),
    isActive: boolean('is_active').notNull().default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    // Supports the "email all active residents" fan-out for important notices.
    index('users_role_is_active_idx').on(table.role, table.isActive),
    // Emails are stored lowercase; this makes that a database guarantee rather
    // than an application convention, so duplicate accounts are impossible.
    check('users_email_lowercase_check', sql`${table.email} = lower(${table.email})`),
  ],
);

/**
 * Opaque server-side sessions.
 *
 * The cookie carries a random 32-byte token; only its SHA-256 hash is stored,
 * so a database leak does not hand an attacker live sessions. Chosen over JWT
 * because we already load the user on every authorized request (to check the
 * role), which means the "stateless" advantage of a JWT would buy nothing —
 * while costing us the ability to revoke a session.
 */
export const sessions = pgTable(
  'sessions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tokenHash: text('token_hash').notNull().unique(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    userAgent: text('user_agent'),
    ipAddress: varchar('ip_address', { length: 64 }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index('sessions_user_id_idx').on(table.userId),
    // Sweep of expired sessions.
    index('sessions_expires_at_idx').on(table.expiresAt),
  ],
);

// ---------------------------------------------------------------------------
// Complaints
// ---------------------------------------------------------------------------

export const complaints = pgTable(
  'complaints',
  {
    id: uuid('id').primaryKey().defaultRandom(),

    /**
     * Human-readable reference such as `CMP-000142`, quoted by residents and
     * in emails.
     *
     * Generated by a PostgreSQL sequence (created in migration 0000, before
     * this table exists) so numbering is atomic under concurrent inserts. An
     * application-side counter would need a read-modify-write and would either
     * race or force table-level locking.
     */
    reference: varchar('reference', { length: 20 })
      .notNull()
      .unique()
      .default(sql`'CMP-' || lpad(nextval('complaint_reference_seq')::text, 6, '0')`),

    residentId: uuid('resident_id')
      .notNull()
      // A resident with complaints must not be deletable — that would orphan
      // an audit trail. Deactivation (is_active = false) is the supported path.
      .references(() => users.id, { onDelete: 'restrict' }),

    title: varchar('title', { length: 120 }).notNull(),
    description: text('description').notNull(),
    category: complaintCategoryEnum('category').notNull(),
    status: complaintStatusEnum('status').notNull().default('OPEN'),
    priority: priorityEnum('priority').notNull().default('MEDIUM'),

    // The binary lives in object storage (Cloudinary); Postgres stores only
    // the reference. Intrinsic dimensions are kept so the UI can reserve space
    // and avoid layout shift.
    photoUrl: text('photo_url'),
    photoPublicId: text('photo_public_id'),
    photoWidth: integer('photo_width'),
    photoHeight: integer('photo_height'),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    /** Denormalised for resolution-time reporting and terminal-state checks. */
    resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  },
  (table) => [
    // Resident's own list, newest first.
    index('complaints_resident_created_idx').on(table.residentId, table.createdAt.desc()),
    /**
     * Serves the admin status filter AND the overdue predicate
     * (status <> 'RESOLVED' AND created_at < cutoff). A leading equality
     * column followed by the range column is precisely what keeps overdue
     * detection an index scan instead of a sequential scan.
     */
    index('complaints_status_created_idx').on(table.status, table.createdAt),
    index('complaints_category_idx').on(table.category),
    index('complaints_priority_created_idx').on(table.priority, table.createdAt.desc()),
    index('complaints_created_at_idx').on(table.createdAt.desc()),
    /**
     * A complaint is resolved if and only if it carries a resolution
     * timestamp. This closes the gap where application code could set one
     * without the other and silently corrupt resolution-time reporting.
     */
    check(
      'complaints_resolved_at_consistency_check',
      sql`(${table.status} = 'RESOLVED') = (${table.resolvedAt} IS NOT NULL)`,
    ),
  ],
);

/**
 * Append-only audit trail for complaints.
 *
 * Every mutation of a complaint's status or priority writes exactly one row
 * here, inside the same transaction as the mutation itself. Rows are never
 * updated or deleted — enforced by a trigger in migration 0001.
 *
 * Modelled as one event log rather than separate status/priority history
 * tables because both record the same shape of fact ("actor X changed field F
 * from A to B at time T, with an optional note"). One table gives the detail
 * timeline as a single ordered query instead of a UNION, and the assignment's
 * "status history" is simply `WHERE type = 'STATUS_CHANGED'`.
 */
export const complaintEvents = pgTable(
  'complaint_events',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    complaintId: uuid('complaint_id')
      .notNull()
      .references(() => complaints.id, { onDelete: 'cascade' }),
    type: complaintEventTypeEnum('type').notNull(),

    fromStatus: complaintStatusEnum('from_status'),
    toStatus: complaintStatusEnum('to_status'),

    fromPriority: priorityEnum('from_priority'),
    toPriority: priorityEnum('to_priority'),

    /** Optional free-text note recorded by the actor alongside the change. */
    note: text('note'),

    actorId: uuid('actor_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),
    /**
     * Snapshot of the actor's role at the moment of the action. An audit record
     * states facts as they were; resolving the role through a join would
     * rewrite history if the user's role later changed.
     */
    actorRole: roleEnum('actor_role').notNull(),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    // Timeline fetch for one complaint, in order.
    index('complaint_events_complaint_created_idx').on(table.complaintId, table.createdAt),
    index('complaint_events_actor_idx').on(table.actorId),
    // "Recent activity" feed on the admin dashboard.
    index('complaint_events_created_at_idx').on(table.createdAt.desc()),
    /**
     * Each event type must carry exactly the fields it is about. Without this,
     * a bug could write a STATUS_CHANGED row with no statuses and the timeline
     * would render a meaningless entry.
     */
    check(
      'complaint_events_payload_check',
      sql`
        (${table.type} = 'CREATED'
           AND ${table.toStatus} IS NOT NULL
           AND ${table.fromStatus} IS NULL)
        OR (${table.type} = 'STATUS_CHANGED'
           AND ${table.fromStatus} IS NOT NULL
           AND ${table.toStatus} IS NOT NULL)
        OR (${table.type} = 'PRIORITY_CHANGED'
           AND ${table.fromPriority} IS NOT NULL
           AND ${table.toPriority} IS NOT NULL)
      `,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Notice board
// ---------------------------------------------------------------------------

export const notices = pgTable(
  'notices',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    title: varchar('title', { length: 160 }).notNull(),
    body: text('body').notNull(),
    /**
     * Important notices pin to the top of the board and trigger an email
     * fan-out to active residents when first published as important.
     */
    isImportant: boolean('is_important').notNull().default(false),

    authorId: uuid('author_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),

    publishedAt: timestamp('published_at', { withTimezone: true }).notNull().defaultNow(),
    /** Soft delete: notices are community record, so they are archived, not erased. */
    archivedAt: timestamp('archived_at', { withTimezone: true }),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    // Exactly the notice-board ordering: pinned first, then newest.
    index('notices_important_published_idx').on(
      table.isImportant.desc(),
      table.publishedAt.desc(),
    ),
    index('notices_archived_at_idx').on(table.archivedAt),
  ],
);

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/**
 * Single-row configuration table.
 *
 * The overdue threshold lives here rather than in an environment variable so
 * an admin can change it at runtime — which is the stronger reading of the
 * requirement "configurable number of days". `OVERDUE_THRESHOLD_DAYS` only
 * seeds the initial value.
 */
export const appSettings = pgTable(
  'app_settings',
  {
    id: integer('id').primaryKey().default(1),
    societyName: varchar('society_name', { length: 120 }).notNull().default('Greenwood Heights'),
    overdueThresholdDays: integer('overdue_threshold_days').notNull().default(7),
    updatedById: uuid('updated_by_id').references(() => users.id, { onDelete: 'set null' }),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    // Makes "there is exactly one settings row" a database guarantee.
    check('app_settings_singleton_check', sql`${table.id} = 1`),
    check(
      'app_settings_threshold_range_check',
      sql`${table.overdueThresholdDays} BETWEEN 1 AND 365`,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Notifications
// ---------------------------------------------------------------------------

/**
 * Transactional-email outbox.
 *
 * A row is inserted inside the same transaction as the domain change that
 * caused it, then dispatched *after* that transaction commits. This keeps
 * email off the critical path: a provider outage can never roll back a
 * complaint update, and every attempt stays auditable and retryable.
 */
export const emailOutbox = pgTable(
  'email_outbox',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    recipientEmail: varchar('recipient_email', { length: 255 }).notNull(),
    recipientName: varchar('recipient_name', { length: 120 }),
    type: emailTypeEnum('type').notNull(),
    subject: text('subject').notNull(),
    status: emailStatusEnum('status').notNull().default('PENDING'),
    attempts: integer('attempts').notNull().default(0),

    providerMessageId: text('provider_message_id'),
    lastError: text('last_error'),

    complaintId: uuid('complaint_id').references(() => complaints.id, { onDelete: 'cascade' }),
    noticeId: uuid('notice_id').references(() => notices.id, { onDelete: 'cascade' }),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    sentAt: timestamp('sent_at', { withTimezone: true }),
  },
  (table) => [
    // Retry sweep over PENDING / FAILED rows.
    index('email_outbox_status_created_idx').on(table.status, table.createdAt),
    index('email_outbox_created_at_idx').on(table.createdAt.desc()),
  ],
);

// ---------------------------------------------------------------------------
// Relations (typed joins for the query builder)
// ---------------------------------------------------------------------------

export const usersRelations = relations(users, ({ many }) => ({
  complaints: many(complaints),
  events: many(complaintEvents),
  notices: many(notices),
  sessions: many(sessions),
}));

export const sessionsRelations = relations(sessions, ({ one }) => ({
  user: one(users, { fields: [sessions.userId], references: [users.id] }),
}));

export const complaintsRelations = relations(complaints, ({ one, many }) => ({
  resident: one(users, { fields: [complaints.residentId], references: [users.id] }),
  events: many(complaintEvents),
  emails: many(emailOutbox),
}));

export const complaintEventsRelations = relations(complaintEvents, ({ one }) => ({
  complaint: one(complaints, { fields: [complaintEvents.complaintId], references: [complaints.id] }),
  actor: one(users, { fields: [complaintEvents.actorId], references: [users.id] }),
}));

export const noticesRelations = relations(notices, ({ one, many }) => ({
  author: one(users, { fields: [notices.authorId], references: [users.id] }),
  emails: many(emailOutbox),
}));

export const emailOutboxRelations = relations(emailOutbox, ({ one }) => ({
  complaint: one(complaints, { fields: [emailOutbox.complaintId], references: [complaints.id] }),
  notice: one(notices, { fields: [emailOutbox.noticeId], references: [notices.id] }),
}));

// ---------------------------------------------------------------------------
// Inferred types — the single source of truth for row shapes across the app.
// ---------------------------------------------------------------------------

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Session = typeof sessions.$inferSelect;
export type Complaint = typeof complaints.$inferSelect;
export type NewComplaint = typeof complaints.$inferInsert;
export type ComplaintEvent = typeof complaintEvents.$inferSelect;
export type NewComplaintEvent = typeof complaintEvents.$inferInsert;
export type Notice = typeof notices.$inferSelect;
export type NewNotice = typeof notices.$inferInsert;
export type AppSetting = typeof appSettings.$inferSelect;
export type EmailOutboxRow = typeof emailOutbox.$inferSelect;

export type Role = (typeof roleEnum.enumValues)[number];
export type ComplaintStatus = (typeof complaintStatusEnum.enumValues)[number];
export type Priority = (typeof priorityEnum.enumValues)[number];
export type ComplaintCategory = (typeof complaintCategoryEnum.enumValues)[number];
export type ComplaintEventType = (typeof complaintEventTypeEnum.enumValues)[number];
export type EmailType = (typeof emailTypeEnum.enumValues)[number];
export type EmailStatus = (typeof emailStatusEnum.enumValues)[number];
